---
version: "3.7"

services:
  _base:
    build:
      context: ".."
      dockerfile: "Dockerfile"
    image: "localhost/oci_env/pulp:base${DEV_IMAGE_SUFFIX}"
    entrypoint: "/bin/true"
    tmpfs:
      - "/var/lib/pulp/artifact"
      - "/var/lib/pulp/scripts"
      - "/var/lib/pulp/tmp"
      - "/tmp/ansible"

  pulp:
    image: "localhost/oci_env/pulp:base${DEV_IMAGE_SUFFIX}"
    tmpfs:
      - "/var/lib/pulp/artifact"
      - "/var/lib/pulp/scripts"
      - "/var/lib/pulp/tmp"
      - "/tmp/ansible"
    env_file:
      - "${COMPOSE_CONTEXT}/.combined.env"
      - "${COMPOSE_CONTEXT}/.compose.env"
    environment:
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
      - "COMPOSE_PROFILE=${COMPOSE_PROFILE}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "NGINX_PORT=${NGINX_PORT}"
      - "NGINX_SSL_PORT=${NGINX_SSL_PORT}"
    ports:
      - "${API_PORT}:${NGINX_PORT}"
    depends_on:
      - _base
    volumes:
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "oci_pulp:/var/lib/pulp"
      - "oci_redis_data:/data"
      - "oci_pg_data:/var/lib/pgsql"

volumes:
  oci_pulp:
    name: oci_pulp${DEV_VOLUME_SUFFIX}
  oci_pg_data:
    name: oci_pg_data${DEV_VOLUME_SUFFIX}
  oci_redis_data:
    name: oci_redis_data${DEV_VOLUME_SUFFIX}
